/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocImageObjectsCrossPageIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocImageObjectsCrossPageIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocImageObjectsCrossPageIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocImageObjectsCrossPageIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocImageObjectsCrossPageIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocImageObjectsCrossPageIterator(DocImageObjectsCrossPageIterator other) {
    this(jnidocengineJNI.new_DocImageObjectsCrossPageIterator(DocImageObjectsCrossPageIterator.getCPtr(other), other), true);
  }

  public int GetPhysicalPageID() {
    return jnidocengineJNI.DocImageObjectsCrossPageIterator_GetPhysicalPageID(swigCPtr, this);
  }

  public int GetObjectID() {
    return jnidocengineJNI.DocImageObjectsCrossPageIterator_GetObjectID(swigCPtr, this);
  }

  public DocImageObject GetImageObject() {
    return new DocImageObject(jnidocengineJNI.DocImageObjectsCrossPageIterator_GetImageObject(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocImageObjectsCrossPageIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocImageObjectsCrossPageIterator rvalue) {
    return jnidocengineJNI.DocImageObjectsCrossPageIterator_Equals(swigCPtr, this, DocImageObjectsCrossPageIterator.getCPtr(rvalue), rvalue);
  }

}
