/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocBasicObjectsCrossSliceIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocBasicObjectsCrossSliceIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocBasicObjectsCrossSliceIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocBasicObjectsCrossSliceIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocBasicObjectsCrossSliceIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBasicObjectsCrossSliceIterator(DocBasicObjectsCrossSliceIterator other) {
    this(jnidocengineJNI.new_DocBasicObjectsCrossSliceIterator(DocBasicObjectsCrossSliceIterator.getCPtr(other), other), true);
  }

  public int GetCollectionID() {
    return jnidocengineJNI.DocBasicObjectsCrossSliceIterator_GetCollectionID(swigCPtr, this);
  }

  public int GetObjectID() {
    return jnidocengineJNI.DocBasicObjectsCrossSliceIterator_GetObjectID(swigCPtr, this);
  }

  public DocBasicObject GetBasicObject() {
    return new DocBasicObject(jnidocengineJNI.DocBasicObjectsCrossSliceIterator_GetBasicObject(swigCPtr, this), false);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocBasicObjectsCrossSliceIterator_GetTags(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocBasicObjectsCrossSliceIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocBasicObjectsCrossSliceIterator rvalue) {
    return jnidocengineJNI.DocBasicObjectsCrossSliceIterator_Equals(swigCPtr, this, DocBasicObjectsCrossSliceIterator.getCPtr(rvalue), rvalue);
  }

}
