/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocObjectsCollectionsMutableSliceIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocObjectsCollectionsMutableSliceIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocObjectsCollectionsMutableSliceIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocObjectsCollectionsMutableSliceIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocObjectsCollectionsMutableSliceIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocObjectsCollectionsMutableSliceIterator(DocObjectsCollectionsMutableSliceIterator other) {
    this(jnidocengineJNI.new_DocObjectsCollectionsMutableSliceIterator(DocObjectsCollectionsMutableSliceIterator.getCPtr(other), other), true);
  }

  public int GetID() {
    return jnidocengineJNI.DocObjectsCollectionsMutableSliceIterator_GetID(swigCPtr, this);
  }

  public DocObjectsCollection GetObjectsCollection() {
    return new DocObjectsCollection(jnidocengineJNI.DocObjectsCollectionsMutableSliceIterator_GetObjectsCollection(swigCPtr, this), false);
  }

  public DocObjectsCollection GetMutableObjectsCollection() {
    return new DocObjectsCollection(jnidocengineJNI.DocObjectsCollectionsMutableSliceIterator_GetMutableObjectsCollection(swigCPtr, this), false);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocObjectsCollectionsMutableSliceIterator_GetTags(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocObjectsCollectionsMutableSliceIterator_Advance(swigCPtr, this);
  }

  public boolean Finished() {
    return jnidocengineJNI.DocObjectsCollectionsMutableSliceIterator_Finished(swigCPtr, this);
  }

}
