/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocTableObjectsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocTableObjectsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocTableObjectsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocTableObjectsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocTableObjectsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocTableObjectsIterator(DocTableObjectsIterator other) {
    this(jnidocengineJNI.new_DocTableObjectsIterator(DocTableObjectsIterator.getCPtr(other), other), true);
  }

  public DocTableObject GetTableObject() {
    return new DocTableObject(jnidocengineJNI.DocTableObjectsIterator_GetTableObject(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocTableObjectsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocTableObjectsIterator rvalue) {
    return jnidocengineJNI.DocTableObjectsIterator_Equals(swigCPtr, this, DocTableObjectsIterator.getCPtr(rvalue), rvalue);
  }

}
