//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.doc {

using se.common;

public class DocTableObject : DocBasicObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public DocTableObject(global::System.IntPtr cPtr, bool cMemoryOwn) : base(csdocenginePINVOKE.DocTableObject_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(DocTableObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(DocTableObject obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csdocenginePINVOKE.delete_DocTableObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public static string ObjectTypeStatic() {
    string ret = csdocenginePINVOKE.DocTableObject_ObjectTypeStatic();
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetRowsCount() {
    int ret = csdocenginePINVOKE.DocTableObject_GetRowsCount(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetColsCount(int row) {
    int ret = csdocenginePINVOKE.DocTableObject_GetColsCount(swigCPtr, row);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void ResizeRows(int rows) {
    csdocenginePINVOKE.DocTableObject_ResizeRows(swigCPtr, rows);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void ResizeCols(int row, int cols) {
    csdocenginePINVOKE.DocTableObject_ResizeCols(swigCPtr, row, cols);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string GetColName(int col, int row) {
    string ret = csdocenginePINVOKE.DocTableObject_GetColName(swigCPtr, col, row);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetColName(int col, int first_row, string col_name) {
    csdocenginePINVOKE.DocTableObject_SetColName(swigCPtr, col, first_row, col_name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual DocTextObject GetTextCell(int row, int col) {
    DocTextObject ret = new DocTextObject(csdocenginePINVOKE.DocTableObject_GetTextCell(swigCPtr, row, col), false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocTextObject GetTextCellPtr(int row, int col) {
    global::System.IntPtr cPtr = csdocenginePINVOKE.DocTableObject_GetTextCellPtr(swigCPtr, row, col);
    DocTextObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new DocTextObject(cPtr, false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocMultiStringTextObject GetCell(int row, int col) {
    DocMultiStringTextObject ret = new DocMultiStringTextObject(csdocenginePINVOKE.DocTableObject_GetCell(swigCPtr, row, col), false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocMultiStringTextObject GetMutableCell(int row, int col) {
    DocMultiStringTextObject ret = new DocMultiStringTextObject(csdocenginePINVOKE.DocTableObject_GetMutableCell(swigCPtr, row, col), false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetCell(int row, int col, DocMultiStringTextObject multi_string_text_object) {
    csdocenginePINVOKE.DocTableObject_SetCell(swigCPtr, row, col, DocMultiStringTextObject.getCPtr(multi_string_text_object));
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
