/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocBasicObjectsMutableCrossSliceIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocBasicObjectsMutableCrossSliceIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocBasicObjectsMutableCrossSliceIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocBasicObjectsMutableCrossSliceIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocBasicObjectsMutableCrossSliceIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBasicObjectsMutableCrossSliceIterator(DocBasicObjectsMutableCrossSliceIterator other) {
    this(jnidocengineJNI.new_DocBasicObjectsMutableCrossSliceIterator(DocBasicObjectsMutableCrossSliceIterator.getCPtr(other), other), true);
  }

  public int GetCollectionID() {
    return jnidocengineJNI.DocBasicObjectsMutableCrossSliceIterator_GetCollectionID(swigCPtr, this);
  }

  public int GetObjectID() {
    return jnidocengineJNI.DocBasicObjectsMutableCrossSliceIterator_GetObjectID(swigCPtr, this);
  }

  public DocBasicObject GetBasicObject() {
    return new DocBasicObject(jnidocengineJNI.DocBasicObjectsMutableCrossSliceIterator_GetBasicObject(swigCPtr, this), false);
  }

  public DocBasicObject GetMutableBasicObject() {
    return new DocBasicObject(jnidocengineJNI.DocBasicObjectsMutableCrossSliceIterator_GetMutableBasicObject(swigCPtr, this), false);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocBasicObjectsMutableCrossSliceIterator_GetTags(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocBasicObjectsMutableCrossSliceIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocBasicObjectsMutableCrossSliceIterator rvalue) {
    return jnidocengineJNI.DocBasicObjectsMutableCrossSliceIterator_Equals(swigCPtr, this, DocBasicObjectsMutableCrossSliceIterator.getCPtr(rvalue), rvalue);
  }

}
