/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocDocumentFieldsInfoIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocDocumentFieldsInfoIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocDocumentFieldsInfoIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocDocumentFieldsInfoIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocDocumentFieldsInfoIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocDocumentFieldsInfoIterator(DocDocumentFieldsInfoIterator other) {
    this(jnidocengineJNI.new_DocDocumentFieldsInfoIterator(DocDocumentFieldsInfoIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jnidocengineJNI.DocDocumentFieldsInfoIterator_GetKey(swigCPtr, this);
  }

  public DocDocumentFieldInfo GetDocumentFieldInfo() {
    return new DocDocumentFieldInfo(jnidocengineJNI.DocDocumentFieldsInfoIterator_GetDocumentFieldInfo(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocDocumentFieldsInfoIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocDocumentFieldsInfoIterator rvalue) {
    return jnidocengineJNI.DocDocumentFieldsInfoIterator_Equals(swigCPtr, this, DocDocumentFieldsInfoIterator.getCPtr(rvalue), rvalue);
  }

}
