//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.doc {

using se.common;

public class DocDocumentTableFieldColumnsInfoInterator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public DocDocumentTableFieldColumnsInfoInterator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(DocDocumentTableFieldColumnsInfoInterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(DocDocumentTableFieldColumnsInfoInterator obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DocDocumentTableFieldColumnsInfoInterator() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csdocenginePINVOKE.delete_DocDocumentTableFieldColumnsInfoInterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DocDocumentTableFieldColumnsInfoInterator(DocDocumentTableFieldColumnsInfoInterator other) : this(csdocenginePINVOKE.new_DocDocumentTableFieldColumnsInfoInterator(DocDocumentTableFieldColumnsInfoInterator.getCPtr(other)), true) {
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetKey() {
    string ret = csdocenginePINVOKE.DocDocumentTableFieldColumnsInfoInterator_GetKey(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DocDocumentTableFieldColumnInfo GetDocumentTableFieldColumnInfo() {
    DocDocumentTableFieldColumnInfo ret = new DocDocumentTableFieldColumnInfo(csdocenginePINVOKE.DocDocumentTableFieldColumnsInfoInterator_GetDocumentTableFieldColumnInfo(swigCPtr), false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DocDocumentTableFieldColumnInfo GetDocumentTableFieldColumnInfoPtr() {
    global::System.IntPtr cPtr = csdocenginePINVOKE.DocDocumentTableFieldColumnsInfoInterator_GetDocumentTableFieldColumnInfoPtr(swigCPtr);
    DocDocumentTableFieldColumnInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new DocDocumentTableFieldColumnInfo(cPtr, false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Advance() {
    csdocenginePINVOKE.DocDocumentTableFieldColumnsInfoInterator_Advance(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Equals(DocDocumentTableFieldColumnsInfoInterator rvalue) {
    bool ret = csdocenginePINVOKE.DocDocumentTableFieldColumnsInfoInterator_Equals(swigCPtr, DocDocumentTableFieldColumnsInfoInterator.getCPtr(rvalue));
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
