/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocBasicObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocBasicObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocBasicObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocBasicObject obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocBasicObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String BaseClassNameStatic() {
    return jnidocengineJNI.DocBasicObject_BaseClassNameStatic();
  }

  public String ObjectType() {
    return jnidocengineJNI.DocBasicObject_ObjectType(swigCPtr, this);
  }

  public DocBaseObjectInfo GetBaseObjectInfo() {
    return new DocBaseObjectInfo(jnidocengineJNI.DocBasicObject_GetBaseObjectInfo(swigCPtr, this), false);
  }

  public DocBaseObjectInfo GetMutableBaseObjectInfo() {
    return new DocBaseObjectInfo(jnidocengineJNI.DocBasicObject_GetMutableBaseObjectInfo(swigCPtr, this), false);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocBasicObject_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
