/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocBasicObjectsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocBasicObjectsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocBasicObjectsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocBasicObjectsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocBasicObjectsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBasicObjectsIterator(DocBasicObjectsIterator other) {
    this(jnidocengineJNI.new_DocBasicObjectsIterator(DocBasicObjectsIterator.getCPtr(other), other), true);
  }

  public int GetID() {
    return jnidocengineJNI.DocBasicObjectsIterator_GetID(swigCPtr, this);
  }

  public DocBasicObject GetBasicObject() {
    return new DocBasicObject(jnidocengineJNI.DocBasicObjectsIterator_GetBasicObject(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocBasicObjectsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocBasicObjectsIterator rvalue) {
    return jnidocengineJNI.DocBasicObjectsIterator_Equals(swigCPtr, this, DocBasicObjectsIterator.getCPtr(rvalue), rvalue);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocBasicObjectsIterator_GetTags(swigCPtr, this), false);
  }

}
