/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocBarcodeField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocBarcodeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocBarcodeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocBarcodeField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocBarcodeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBaseFieldInfo GetBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocBarcodeField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public DocBaseFieldInfo GetMutableBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocBarcodeField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

  public MutableString GetDecodedString() {
    return new MutableString(jnidocengineJNI.DocBarcodeField_GetDecodedString(swigCPtr, this), false);
  }

  public MutableString GetMutableDecodedString() {
    return new MutableString(jnidocengineJNI.DocBarcodeField_GetMutableDecodedString(swigCPtr, this), false);
  }

  public void SetDecodedString(MutableString decstring) {
    jnidocengineJNI.DocBarcodeField_SetDecodedString(swigCPtr, this, MutableString.getCPtr(decstring), decstring);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocBarcodeField_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
