/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocEngine {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocEngine obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocSessionSettings CreateSessionSettings() {
    long cPtr = jnidocengineJNI.DocEngine_CreateSessionSettings(swigCPtr, this);
    return (cPtr == 0) ? null : new DocSessionSettings(cPtr, true);
  }

  public DocSession SpawnSession(DocSessionSettings settings, String signature, DocFeedback feedback_reporter) {
    long cPtr = jnidocengineJNI.DocEngine_SpawnSession__SWIG_0(swigCPtr, this, DocSessionSettings.getCPtr(settings), settings, signature, DocFeedback.getCPtr(feedback_reporter), feedback_reporter);
    return (cPtr == 0) ? null : new DocSession(cPtr, true);
  }

  public DocSession SpawnSession(DocSessionSettings settings, String signature) {
    long cPtr = jnidocengineJNI.DocEngine_SpawnSession__SWIG_1(swigCPtr, this, DocSessionSettings.getCPtr(settings), settings, signature);
    return (cPtr == 0) ? null : new DocSession(cPtr, true);
  }

  public static DocEngine Create(String config_path, boolean lazy_configuration) {
    long cPtr = jnidocengineJNI.DocEngine_Create__SWIG_0(config_path, lazy_configuration);
    return (cPtr == 0) ? null : new DocEngine(cPtr, true);
  }

  public static DocEngine Create(String config_path) {
    long cPtr = jnidocengineJNI.DocEngine_Create__SWIG_1(config_path);
    return (cPtr == 0) ? null : new DocEngine(cPtr, true);
  }

  public static DocEngine Create(byte[] config_data, boolean lazy_configuration) {
    long cPtr = jnidocengineJNI.DocEngine_Create__SWIG_2(config_data, lazy_configuration);
    return (cPtr == 0) ? null : new DocEngine(cPtr, true);
  }

  public static DocEngine Create(byte[] config_data) {
    long cPtr = jnidocengineJNI.DocEngine_Create__SWIG_3(config_data);
    return (cPtr == 0) ? null : new DocEngine(cPtr, true);
  }

  public static DocEngine CreateFromEmbeddedBundle(boolean lazy_configuration) {
    long cPtr = jnidocengineJNI.DocEngine_CreateFromEmbeddedBundle__SWIG_0(lazy_configuration);
    return (cPtr == 0) ? null : new DocEngine(cPtr, true);
  }

  public static DocEngine CreateFromEmbeddedBundle() {
    long cPtr = jnidocengineJNI.DocEngine_CreateFromEmbeddedBundle__SWIG_1();
    return (cPtr == 0) ? null : new DocEngine(cPtr, true);
  }

  public static String GetVersion() {
    return jnidocengineJNI.DocEngine_GetVersion();
  }

  public DocSession SpawnSession(DocSessionSettings settings, String signature, DocFeedback feedback_reporter, DocExternalProcessorInterface external_processor) {
    long cPtr = jnidocengineJNI.DocEngine_SpawnSession__SWIG_2(swigCPtr, this, DocSessionSettings.getCPtr(settings), settings, signature, DocFeedback.getCPtr(feedback_reporter), feedback_reporter, DocExternalProcessorInterface.getCPtr(external_processor), external_processor);
    return (cPtr == 0) ? null : new DocSession(cPtr, true);
  }

  public DocSessionSettings CreateVideoSessionSettings() {
    long cPtr = jnidocengineJNI.DocEngine_CreateVideoSessionSettings(swigCPtr, this);
    return (cPtr == 0) ? null : new DocSessionSettings(cPtr, true);
  }

  public DocVideoSession SpawnVideoSession(DocSessionSettings settings, String signature, DocFeedback feedback_reporter) {
    long cPtr = jnidocengineJNI.DocEngine_SpawnVideoSession__SWIG_0(swigCPtr, this, DocSessionSettings.getCPtr(settings), settings, signature, DocFeedback.getCPtr(feedback_reporter), feedback_reporter);
    return (cPtr == 0) ? null : new DocVideoSession(cPtr, true);
  }

  public DocVideoSession SpawnVideoSession(DocSessionSettings settings, String signature) {
    long cPtr = jnidocengineJNI.DocEngine_SpawnVideoSession__SWIG_1(swigCPtr, this, DocSessionSettings.getCPtr(settings), settings, signature);
    return (cPtr == 0) ? null : new DocVideoSession(cPtr, true);
  }

}
