/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocForensicField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocForensicField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocForensicField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocForensicField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocForensicField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBaseFieldInfo GetBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocForensicField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public DocBaseFieldInfo GetMutableBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocForensicField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

  public String GetStatus() {
    return jnidocengineJNI.DocForensicField_GetStatus(swigCPtr, this);
  }

  public void SetStatus(String status) {
    jnidocengineJNI.DocForensicField_SetStatus(swigCPtr, this, status);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocForensicField_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
