/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocImageField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocImageField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocImageField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocImageField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocImageField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBaseFieldInfo GetBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocImageField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public DocBaseFieldInfo GetMutableBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocImageField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

  public Image GetImage() {
    return new Image(jnidocengineJNI.DocImageField_GetImage(swigCPtr, this), false);
  }

  public Image GetMutableImage() {
    return new Image(jnidocengineJNI.DocImageField_GetMutableImage(swigCPtr, this), false);
  }

  public void SetImage(Image image) {
    jnidocengineJNI.DocImageField_SetImage(swigCPtr, this, Image.getCPtr(image), image);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocImageField_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
