/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class Document {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Document(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Document obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Document obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_Document(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String BaseClassNameStatic() {
    return jnidocengineJNI.Document_BaseClassNameStatic();
  }

  public int GetTextFieldsCount() {
    return jnidocengineJNI.Document_GetTextFieldsCount(swigCPtr, this);
  }

  public boolean HasTextField(String name) {
    return jnidocengineJNI.Document_HasTextField(swigCPtr, this, name);
  }

  public DocTextField GetTextField(String name) {
    return new DocTextField(jnidocengineJNI.Document_GetTextField(swigCPtr, this, name), false);
  }

  public DocTextField GetMutableTextField(String name) {
    return new DocTextField(jnidocengineJNI.Document_GetMutableTextField(swigCPtr, this, name), false);
  }

  public void SetTextField(String name, DocTextField field) {
    jnidocengineJNI.Document_SetTextField(swigCPtr, this, name, DocTextField.getCPtr(field), field);
  }

  public void RemoveTextField(String name) {
    jnidocengineJNI.Document_RemoveTextField(swigCPtr, this, name);
  }

  public DocTextFieldsIterator TextFieldsBegin() {
    return new DocTextFieldsIterator(jnidocengineJNI.Document_TextFieldsBegin(swigCPtr, this), true);
  }

  public DocTextFieldsIterator TextFieldsEnd() {
    return new DocTextFieldsIterator(jnidocengineJNI.Document_TextFieldsEnd(swigCPtr, this), true);
  }

  public int GetImageFieldsCount() {
    return jnidocengineJNI.Document_GetImageFieldsCount(swigCPtr, this);
  }

  public boolean HasImageField(String name) {
    return jnidocengineJNI.Document_HasImageField(swigCPtr, this, name);
  }

  public DocImageField GetImageField(String name) {
    return new DocImageField(jnidocengineJNI.Document_GetImageField(swigCPtr, this, name), false);
  }

  public DocImageField GetMutableImageField(String name) {
    return new DocImageField(jnidocengineJNI.Document_GetMutableImageField(swigCPtr, this, name), false);
  }

  public void SetImageField(String name, DocImageField field) {
    jnidocengineJNI.Document_SetImageField(swigCPtr, this, name, DocImageField.getCPtr(field), field);
  }

  public void RemoveImageField(String name) {
    jnidocengineJNI.Document_RemoveImageField(swigCPtr, this, name);
  }

  public DocImageFieldsIterator ImageFieldsBegin() {
    return new DocImageFieldsIterator(jnidocengineJNI.Document_ImageFieldsBegin(swigCPtr, this), true);
  }

  public DocImageFieldsIterator ImageFieldsEnd() {
    return new DocImageFieldsIterator(jnidocengineJNI.Document_ImageFieldsEnd(swigCPtr, this), true);
  }

  public int GetCheckboxFieldsCount() {
    return jnidocengineJNI.Document_GetCheckboxFieldsCount(swigCPtr, this);
  }

  public boolean HasCheckboxField(String name) {
    return jnidocengineJNI.Document_HasCheckboxField(swigCPtr, this, name);
  }

  public DocCheckboxField GetCheckboxField(String name) {
    return new DocCheckboxField(jnidocengineJNI.Document_GetCheckboxField(swigCPtr, this, name), false);
  }

  public DocCheckboxField GetMutableCheckboxField(String name) {
    return new DocCheckboxField(jnidocengineJNI.Document_GetMutableCheckboxField(swigCPtr, this, name), false);
  }

  public void SetCheckboxField(String name, DocCheckboxField field) {
    jnidocengineJNI.Document_SetCheckboxField(swigCPtr, this, name, DocCheckboxField.getCPtr(field), field);
  }

  public void RemoveCheckboxField(String name) {
    jnidocengineJNI.Document_RemoveCheckboxField(swigCPtr, this, name);
  }

  public DocCheckboxFieldsIterator CheckboxFieldsBegin() {
    return new DocCheckboxFieldsIterator(jnidocengineJNI.Document_CheckboxFieldsBegin(swigCPtr, this), true);
  }

  public DocCheckboxFieldsIterator CheckboxFieldsEnd() {
    return new DocCheckboxFieldsIterator(jnidocengineJNI.Document_CheckboxFieldsEnd(swigCPtr, this), true);
  }

  public int GetForensicFieldsCount() {
    return jnidocengineJNI.Document_GetForensicFieldsCount(swigCPtr, this);
  }

  public boolean HasForensicField(String name) {
    return jnidocengineJNI.Document_HasForensicField(swigCPtr, this, name);
  }

  public DocForensicField GetForensicField(String name) {
    return new DocForensicField(jnidocengineJNI.Document_GetForensicField(swigCPtr, this, name), false);
  }

  public DocForensicField GetMutableForensicField(String name) {
    return new DocForensicField(jnidocengineJNI.Document_GetMutableForensicField(swigCPtr, this, name), false);
  }

  public void SetForensicField(String name, DocForensicField field) {
    jnidocengineJNI.Document_SetForensicField(swigCPtr, this, name, DocForensicField.getCPtr(field), field);
  }

  public void RemoveForensicField(String name) {
    jnidocengineJNI.Document_RemoveForensicField(swigCPtr, this, name);
  }

  public DocForensicFieldsIterator ForensicFieldsBegin() {
    return new DocForensicFieldsIterator(jnidocengineJNI.Document_ForensicFieldsBegin(swigCPtr, this), true);
  }

  public DocForensicFieldsIterator ForensicFieldsEnd() {
    return new DocForensicFieldsIterator(jnidocengineJNI.Document_ForensicFieldsEnd(swigCPtr, this), true);
  }

  public int GetForensicCheckFieldsCount() {
    return jnidocengineJNI.Document_GetForensicCheckFieldsCount(swigCPtr, this);
  }

  public boolean HasForensicCheckField(String name) {
    return jnidocengineJNI.Document_HasForensicCheckField(swigCPtr, this, name);
  }

  public DocForensicCheckField GetForensicCheckField(String name) {
    return new DocForensicCheckField(jnidocengineJNI.Document_GetForensicCheckField(swigCPtr, this, name), false);
  }

  public DocForensicCheckField GetMutableForensicCheckField(String name) {
    return new DocForensicCheckField(jnidocengineJNI.Document_GetMutableForensicCheckField(swigCPtr, this, name), false);
  }

  public DocForensicCheckField GetForensicCheckFieldPtr(String name) {
    long cPtr = jnidocengineJNI.Document_GetForensicCheckFieldPtr(swigCPtr, this, name);
    return (cPtr == 0) ? null : new DocForensicCheckField(cPtr, false);
  }

  public DocForensicCheckField GetMutableForensicCheckFieldPtr(String name) {
    long cPtr = jnidocengineJNI.Document_GetMutableForensicCheckFieldPtr(swigCPtr, this, name);
    return (cPtr == 0) ? null : new DocForensicCheckField(cPtr, false);
  }

  public void SetForensicCheckField(String name, DocForensicCheckField field) {
    jnidocengineJNI.Document_SetForensicCheckField(swigCPtr, this, name, DocForensicCheckField.getCPtr(field), field);
  }

  public void RemoveForensicCheckField(String name) {
    jnidocengineJNI.Document_RemoveForensicCheckField(swigCPtr, this, name);
  }

  public DocForensicCheckFieldsIterator ForensicCheckFieldsBegin() {
    return new DocForensicCheckFieldsIterator(jnidocengineJNI.Document_ForensicCheckFieldsBegin(swigCPtr, this), true);
  }

  public DocForensicCheckFieldsIterator ForensicCheckFieldsEnd() {
    return new DocForensicCheckFieldsIterator(jnidocengineJNI.Document_ForensicCheckFieldsEnd(swigCPtr, this), true);
  }

  public int GetTableFieldsCount() {
    return jnidocengineJNI.Document_GetTableFieldsCount(swigCPtr, this);
  }

  public boolean HasTableField(String name) {
    return jnidocengineJNI.Document_HasTableField(swigCPtr, this, name);
  }

  public DocTableField GetTableField(String name) {
    return new DocTableField(jnidocengineJNI.Document_GetTableField(swigCPtr, this, name), false);
  }

  public DocTableField GetMutableTableField(String name) {
    return new DocTableField(jnidocengineJNI.Document_GetMutableTableField(swigCPtr, this, name), false);
  }

  public void SetTableField(String name, DocTableField field) {
    jnidocengineJNI.Document_SetTableField(swigCPtr, this, name, DocTableField.getCPtr(field), field);
  }

  public void RemoveTableField(String name) {
    jnidocengineJNI.Document_RemoveTableField(swigCPtr, this, name);
  }

  public DocTableFieldsIterator TableFieldsBegin() {
    return new DocTableFieldsIterator(jnidocengineJNI.Document_TableFieldsBegin(swigCPtr, this), true);
  }

  public DocTableFieldsIterator TableFieldsEnd() {
    return new DocTableFieldsIterator(jnidocengineJNI.Document_TableFieldsEnd(swigCPtr, this), true);
  }

  public int GetBarcodeFieldsCount() {
    return jnidocengineJNI.Document_GetBarcodeFieldsCount(swigCPtr, this);
  }

  public boolean HasBarcodeField(String name) {
    return jnidocengineJNI.Document_HasBarcodeField(swigCPtr, this, name);
  }

  public DocBarcodeField GetBarcodeField(String name) {
    return new DocBarcodeField(jnidocengineJNI.Document_GetBarcodeField(swigCPtr, this, name), false);
  }

  public DocBarcodeField GetMutableBarcodeField(String name) {
    return new DocBarcodeField(jnidocengineJNI.Document_GetMutableBarcodeField(swigCPtr, this, name), false);
  }

  public void SetBarcodeField(String name, DocBarcodeField field) {
    jnidocengineJNI.Document_SetBarcodeField(swigCPtr, this, name, DocBarcodeField.getCPtr(field), field);
  }

  public void RemoveBarcodeField(String name) {
    jnidocengineJNI.Document_RemoveBarcodeField(swigCPtr, this, name);
  }

  public DocBarcodeFieldsIterator BarcodeFieldsBegin() {
    return new DocBarcodeFieldsIterator(jnidocengineJNI.Document_BarcodeFieldsBegin(swigCPtr, this), true);
  }

  public DocBarcodeFieldsIterator BarcodeFieldsEnd() {
    return new DocBarcodeFieldsIterator(jnidocengineJNI.Document_BarcodeFieldsEnd(swigCPtr, this), true);
  }

  public int GetAttributesCount() {
    return jnidocengineJNI.Document_GetAttributesCount(swigCPtr, this);
  }

  public boolean HasAttribute(String attr_name) {
    return jnidocengineJNI.Document_HasAttribute(swigCPtr, this, attr_name);
  }

  public String GetAttribute(String attr_name) {
    return jnidocengineJNI.Document_GetAttribute(swigCPtr, this, attr_name);
  }

  public void SetAttribute(String attr_name, String attr_value) {
    jnidocengineJNI.Document_SetAttribute(swigCPtr, this, attr_name, attr_value);
  }

  public void RemoveAttribute(String attr_name) {
    jnidocengineJNI.Document_RemoveAttribute(swigCPtr, this, attr_name);
  }

  public StringsMapIterator AttributesBegin() {
    return new StringsMapIterator(jnidocengineJNI.Document_AttributesBegin(swigCPtr, this), true);
  }

  public StringsMapIterator AttributesEnd() {
    return new StringsMapIterator(jnidocengineJNI.Document_AttributesEnd(swigCPtr, this), true);
  }

  public String GetType() {
    return jnidocengineJNI.Document_GetType(swigCPtr, this);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.Document_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

  public int GetPhysicalDocIdx() {
    return jnidocengineJNI.Document_GetPhysicalDocIdx(swigCPtr, this);
  }

}
