/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocumentsMutableSliceIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocumentsMutableSliceIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocumentsMutableSliceIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocumentsMutableSliceIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocumentsMutableSliceIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocumentsMutableSliceIterator(DocumentsMutableSliceIterator other) {
    this(jnidocengineJNI.new_DocumentsMutableSliceIterator(DocumentsMutableSliceIterator.getCPtr(other), other), true);
  }

  public int GetID() {
    return jnidocengineJNI.DocumentsMutableSliceIterator_GetID(swigCPtr, this);
  }

  public Document GetDocument() {
    return new Document(jnidocengineJNI.DocumentsMutableSliceIterator_GetDocument(swigCPtr, this), false);
  }

  public Document GetMutableDocument() {
    return new Document(jnidocengineJNI.DocumentsMutableSliceIterator_GetMutableDocument(swigCPtr, this), false);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocumentsMutableSliceIterator_GetTags(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocumentsMutableSliceIterator_Advance(swigCPtr, this);
  }

  public boolean Finished() {
    return jnidocengineJNI.DocumentsMutableSliceIterator_Finished(swigCPtr, this);
  }

}
