/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocImageFieldsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocImageFieldsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocImageFieldsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocImageFieldsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocImageFieldsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocImageFieldsIterator(DocImageFieldsIterator other) {
    this(jnidocengineJNI.new_DocImageFieldsIterator(DocImageFieldsIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jnidocengineJNI.DocImageFieldsIterator_GetKey(swigCPtr, this);
  }

  public DocImageField GetField() {
    return new DocImageField(jnidocengineJNI.DocImageFieldsIterator_GetField(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocImageFieldsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocImageFieldsIterator rvalue) {
    return jnidocengineJNI.DocImageFieldsIterator_Equals(swigCPtr, this, DocImageFieldsIterator.getCPtr(rvalue), rvalue);
  }

}
