/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocTagsCollection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocTagsCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocTagsCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocTagsCollection obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocTagsCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetTagsCount() {
    return jnidocengineJNI.DocTagsCollection_GetTagsCount(swigCPtr, this);
  }

  public boolean HasTag(String tag) {
    return jnidocengineJNI.DocTagsCollection_HasTag(swigCPtr, this, tag);
  }

  public void AddTag(String tag) {
    jnidocengineJNI.DocTagsCollection_AddTag(swigCPtr, this, tag);
  }

  public void RemoveTag(String tag) {
    jnidocengineJNI.DocTagsCollection_RemoveTag(swigCPtr, this, tag);
  }

  public StringsSetIterator TagsBegin() {
    return new StringsSetIterator(jnidocengineJNI.DocTagsCollection_TagsBegin(swigCPtr, this), true);
  }

  public StringsSetIterator TagsEnd() {
    return new StringsSetIterator(jnidocengineJNI.DocTagsCollection_TagsEnd(swigCPtr, this), true);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocTagsCollection_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

  public static DocTagsCollection Create() {
    long cPtr = jnidocengineJNI.DocTagsCollection_Create();
    return (cPtr == 0) ? null : new DocTagsCollection(cPtr, true);
  }

}
