/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocCheckboxObjectsCrossPageIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocCheckboxObjectsCrossPageIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocCheckboxObjectsCrossPageIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocCheckboxObjectsCrossPageIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocCheckboxObjectsCrossPageIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocCheckboxObjectsCrossPageIterator(DocCheckboxObjectsCrossPageIterator other) {
    this(jnidocengineJNI.new_DocCheckboxObjectsCrossPageIterator(DocCheckboxObjectsCrossPageIterator.getCPtr(other), other), true);
  }

  public int GetPhysicalPageID() {
    return jnidocengineJNI.DocCheckboxObjectsCrossPageIterator_GetPhysicalPageID(swigCPtr, this);
  }

  public int GetObjectID() {
    return jnidocengineJNI.DocCheckboxObjectsCrossPageIterator_GetObjectID(swigCPtr, this);
  }

  public DocCheckboxObject GetCheckboxObject() {
    return new DocCheckboxObject(jnidocengineJNI.DocCheckboxObjectsCrossPageIterator_GetCheckboxObject(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocCheckboxObjectsCrossPageIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocCheckboxObjectsCrossPageIterator rvalue) {
    return jnidocengineJNI.DocCheckboxObjectsCrossPageIterator_Equals(swigCPtr, this, DocCheckboxObjectsCrossPageIterator.getCPtr(rvalue), rvalue);
  }

}
