/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocDocumentTableFieldColumnInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocDocumentTableFieldColumnInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocDocumentTableFieldColumnInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocDocumentTableFieldColumnInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocDocumentTableFieldColumnInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String GetDocumentTableFieldColumnName() {
    return jnidocengineJNI.DocDocumentTableFieldColumnInfo_GetDocumentTableFieldColumnName(swigCPtr, this);
  }

  public String GetDocumentTableFieldColumnNameLocal() {
    return jnidocengineJNI.DocDocumentTableFieldColumnInfo_GetDocumentTableFieldColumnNameLocal(swigCPtr, this);
  }

  public String GetDocumentTableFieldColumnShortNameLocal() {
    return jnidocengineJNI.DocDocumentTableFieldColumnInfo_GetDocumentTableFieldColumnShortNameLocal(swigCPtr, this);
  }

  public String GetDocumentTableFieldColumnFormat() {
    return jnidocengineJNI.DocDocumentTableFieldColumnInfo_GetDocumentTableFieldColumnFormat(swigCPtr, this);
  }

  public String GetDocumentTableFieldColumnExtFormat() {
    return jnidocengineJNI.DocDocumentTableFieldColumnInfo_GetDocumentTableFieldColumnExtFormat(swigCPtr, this);
  }

  public String GetDocumentTableFieldColumnType() {
    return jnidocengineJNI.DocDocumentTableFieldColumnInfo_GetDocumentTableFieldColumnType(swigCPtr, this);
  }

}
