//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.doc {

using se.common;

public class DocPhysicalDocument : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public DocPhysicalDocument(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(DocPhysicalDocument obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(DocPhysicalDocument obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DocPhysicalDocument() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csdocenginePINVOKE.delete_DocPhysicalDocument(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual int GetTextObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetTextObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetTableObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetTableObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetImageObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetImageObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetForensicObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetForensicObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetForensicCheckObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetForensicCheckObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetBarcodeObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetBarcodeObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetCheckboxObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetCheckboxObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetPagesCount() {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetPagesCount(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocPhysicalPage GetPhysicalPage(int idx) {
    DocPhysicalPage ret = new DocPhysicalPage(csdocenginePINVOKE.DocPhysicalDocument_GetPhysicalPage(swigCPtr, idx), false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocPhysicalPage GetPhysicalPagePtr(int idx) {
    global::System.IntPtr cPtr = csdocenginePINVOKE.DocPhysicalDocument_GetPhysicalPagePtr(swigCPtr, idx);
    DocPhysicalPage ret = (cPtr == global::System.IntPtr.Zero) ? null : new DocPhysicalPage(cPtr, false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int GetBasicObjectsCount(string name) {
    int ret = csdocenginePINVOKE.DocPhysicalDocument_GetBasicObjectsCount(swigCPtr, name);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
