//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.doc {

using se.common;

public class DocBarcodeObjectsCrossPageIterator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public DocBarcodeObjectsCrossPageIterator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(DocBarcodeObjectsCrossPageIterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(DocBarcodeObjectsCrossPageIterator obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DocBarcodeObjectsCrossPageIterator() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csdocenginePINVOKE.delete_DocBarcodeObjectsCrossPageIterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DocBarcodeObjectsCrossPageIterator(DocBarcodeObjectsCrossPageIterator other) : this(csdocenginePINVOKE.new_DocBarcodeObjectsCrossPageIterator(DocBarcodeObjectsCrossPageIterator.getCPtr(other)), true) {
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetPhysicalPageID() {
    int ret = csdocenginePINVOKE.DocBarcodeObjectsCrossPageIterator_GetPhysicalPageID(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetObjectID() {
    int ret = csdocenginePINVOKE.DocBarcodeObjectsCrossPageIterator_GetObjectID(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DocBarcodeObject GetBarcodeObject() {
    DocBarcodeObject ret = new DocBarcodeObject(csdocenginePINVOKE.DocBarcodeObjectsCrossPageIterator_GetBarcodeObject(swigCPtr), false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DocBarcodeObject GetBarcodeObjectPtr() {
    global::System.IntPtr cPtr = csdocenginePINVOKE.DocBarcodeObjectsCrossPageIterator_GetBarcodeObjectPtr(swigCPtr);
    DocBarcodeObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new DocBarcodeObject(cPtr, false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Advance() {
    csdocenginePINVOKE.DocBarcodeObjectsCrossPageIterator_Advance(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Equals(DocBarcodeObjectsCrossPageIterator rvalue) {
    bool ret = csdocenginePINVOKE.DocBarcodeObjectsCrossPageIterator_Equals(swigCPtr, DocBarcodeObjectsCrossPageIterator.getCPtr(rvalue));
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
