//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.doc {

using se.common;

public class DocDocumentFieldInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public DocDocumentFieldInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(DocDocumentFieldInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(DocDocumentFieldInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DocDocumentFieldInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csdocenginePINVOKE.delete_DocDocumentFieldInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual string GetDocumentFieldName() {
    string ret = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentFieldName(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetDocumentFieldNameLocal() {
    string ret = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentFieldNameLocal(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetDocumentFieldShortNameLocal() {
    string ret = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentFieldShortNameLocal(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetDocumentFieldFormat() {
    string ret = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentFieldFormat(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetDocumentFieldExtFormat() {
    string ret = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentFieldExtFormat(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetDocumentFieldType() {
    string ret = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentFieldType(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetDocumentFieldCategory() {
    string ret = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentFieldCategory(swigCPtr);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocDocumentTableFieldColumnsInfoInterator DocumentTableFieldColumnsInfoInteratorBegin() {
    DocDocumentTableFieldColumnsInfoInterator ret = new DocDocumentTableFieldColumnsInfoInterator(csdocenginePINVOKE.DocDocumentFieldInfo_DocumentTableFieldColumnsInfoInteratorBegin(swigCPtr), true);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocDocumentTableFieldColumnsInfoInterator DocumentTableFieldColumnsInfoInteratorEnd() {
    DocDocumentTableFieldColumnsInfoInterator ret = new DocDocumentTableFieldColumnsInfoInterator(csdocenginePINVOKE.DocDocumentFieldInfo_DocumentTableFieldColumnsInfoInteratorEnd(swigCPtr), true);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocDocumentTableFieldColumnInfo GetDocumentTableFieldColumnInfo(string name) {
    DocDocumentTableFieldColumnInfo ret = new DocDocumentTableFieldColumnInfo(csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentTableFieldColumnInfo(swigCPtr, name), false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual DocDocumentTableFieldColumnInfo GetDocumentTableFieldColumnInfoPtr(string name) {
    global::System.IntPtr cPtr = csdocenginePINVOKE.DocDocumentFieldInfo_GetDocumentTableFieldColumnInfoPtr(swigCPtr, name);
    DocDocumentTableFieldColumnInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new DocDocumentTableFieldColumnInfo(cPtr, false);
    if (csdocenginePINVOKE.SWIGPendingException.Pending) throw csdocenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
