/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocProcessingArguments {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocProcessingArguments(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocProcessingArguments obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocProcessingArguments obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocProcessingArguments(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetTagArgumentsCount() {
    return jnidocengineJNI.DocProcessingArguments_GetTagArgumentsCount(swigCPtr, this);
  }

  public String GetTagArgument(int index) {
    return jnidocengineJNI.DocProcessingArguments_GetTagArgument(swigCPtr, this, index);
  }

  public void SetTagArgument(int index, String argument) {
    jnidocengineJNI.DocProcessingArguments_SetTagArgument(swigCPtr, this, index, argument);
  }

  public void Resize(int size) {
    jnidocengineJNI.DocProcessingArguments_Resize(swigCPtr, this, size);
  }

}
