/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocViewsMutableIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocViewsMutableIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocViewsMutableIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocViewsMutableIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocViewsMutableIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocViewsMutableIterator(DocViewsMutableIterator other) {
    this(jnidocengineJNI.new_DocViewsMutableIterator(DocViewsMutableIterator.getCPtr(other), other), true);
  }

  public int GetID() {
    return jnidocengineJNI.DocViewsMutableIterator_GetID(swigCPtr, this);
  }

  public DocView GetView() {
    return new DocView(jnidocengineJNI.DocViewsMutableIterator_GetView(swigCPtr, this), false);
  }

  public DocView GetMutableView() {
    return new DocView(jnidocengineJNI.DocViewsMutableIterator_GetMutableView(swigCPtr, this), false);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocViewsMutableIterator_GetTags(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocViewsMutableIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocViewsMutableIterator rvalue) {
    return jnidocengineJNI.DocViewsMutableIterator_Equals(swigCPtr, this, DocViewsMutableIterator.getCPtr(rvalue), rvalue);
  }

}
