/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocCheckboxField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocCheckboxField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocCheckboxField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocCheckboxField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocCheckboxField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBaseFieldInfo GetBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocCheckboxField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public DocBaseFieldInfo GetMutableBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocCheckboxField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

  public boolean GetTickStatus() {
    return jnidocengineJNI.DocCheckboxField_GetTickStatus(swigCPtr, this);
  }

  public void SetTickStatus(boolean tick_status) {
    jnidocengineJNI.DocCheckboxField_SetTickStatus(swigCPtr, this, tick_status);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocCheckboxField_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
