/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocForensicCheckObjectsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocForensicCheckObjectsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocForensicCheckObjectsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocForensicCheckObjectsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocForensicCheckObjectsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocForensicCheckObjectsIterator(DocForensicCheckObjectsIterator other) {
    this(jnidocengineJNI.new_DocForensicCheckObjectsIterator(DocForensicCheckObjectsIterator.getCPtr(other), other), true);
  }

  public DocForensicCheckObject GetForensicCheckObject() {
    return new DocForensicCheckObject(jnidocengineJNI.DocForensicCheckObjectsIterator_GetForensicCheckObject(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocForensicCheckObjectsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocForensicCheckObjectsIterator rvalue) {
    return jnidocengineJNI.DocForensicCheckObjectsIterator_Equals(swigCPtr, this, DocForensicCheckObjectsIterator.getCPtr(rvalue), rvalue);
  }

}
