/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocMetaObjectsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocMetaObjectsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocMetaObjectsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocMetaObjectsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocMetaObjectsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocMetaObjectsIterator(DocMetaObjectsIterator other) {
    this(jnidocengineJNI.new_DocMetaObjectsIterator(DocMetaObjectsIterator.getCPtr(other), other), true);
  }

  public DocMetaObject GetMetaObject() {
    return new DocMetaObject(jnidocengineJNI.DocMetaObjectsIterator_GetMetaObject(swigCPtr, this), false);
  }

  public DocMetaObject GetMetaObjectPtr() {
    long cPtr = jnidocengineJNI.DocMetaObjectsIterator_GetMetaObjectPtr(swigCPtr, this);
    return (cPtr == 0) ? null : new DocMetaObject(cPtr, false);
  }

  public void Advance() {
    jnidocengineJNI.DocMetaObjectsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocMetaObjectsIterator rvalue) {
    return jnidocengineJNI.DocMetaObjectsIterator_Equals(swigCPtr, this, DocMetaObjectsIterator.getCPtr(rvalue), rvalue);
  }

}
