/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocPhysicalDocument {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocPhysicalDocument(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocPhysicalDocument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocPhysicalDocument obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocPhysicalDocument(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetTextObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetTextObjectsCount(swigCPtr, this, name);
  }

  public int GetTableObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetTableObjectsCount(swigCPtr, this, name);
  }

  public int GetImageObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetImageObjectsCount(swigCPtr, this, name);
  }

  public int GetForensicObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetForensicObjectsCount(swigCPtr, this, name);
  }

  public int GetForensicCheckObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetForensicCheckObjectsCount(swigCPtr, this, name);
  }

  public int GetBarcodeObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetBarcodeObjectsCount(swigCPtr, this, name);
  }

  public int GetCheckboxObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetCheckboxObjectsCount(swigCPtr, this, name);
  }

  public int GetPagesCount() {
    return jnidocengineJNI.DocPhysicalDocument_GetPagesCount(swigCPtr, this);
  }

  public DocPhysicalPage GetPhysicalPage(int idx) {
    return new DocPhysicalPage(jnidocengineJNI.DocPhysicalDocument_GetPhysicalPage(swigCPtr, this, idx), false);
  }

  public DocPhysicalPage GetPhysicalPagePtr(int idx) {
    long cPtr = jnidocengineJNI.DocPhysicalDocument_GetPhysicalPagePtr(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new DocPhysicalPage(cPtr, false);
  }

  public int GetBasicObjectsCount(String name) {
    return jnidocengineJNI.DocPhysicalDocument_GetBasicObjectsCount(swigCPtr, this, name);
  }

}
