/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocTableField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocTableField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocTableField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocTableField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocTableField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocBaseFieldInfo GetBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocTableField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public DocBaseFieldInfo GetMutableBaseFieldInfo() {
    return new DocBaseFieldInfo(jnidocengineJNI.DocTableField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

  public int GetRowsCount() {
    return jnidocengineJNI.DocTableField_GetRowsCount(swigCPtr, this);
  }

  public int GetColsCount() {
    return jnidocengineJNI.DocTableField_GetColsCount(swigCPtr, this);
  }

  public DocTextField GetCell(int row, int col) {
    return new DocTextField(jnidocengineJNI.DocTableField_GetCell(swigCPtr, this, row, col), false);
  }

  public DocTextField GetMutableCell(int row, int col) {
    return new DocTextField(jnidocengineJNI.DocTableField_GetMutableCell(swigCPtr, this, row, col), false);
  }

  public void SetCell(int row, int col, DocTextField text_field) {
    jnidocengineJNI.DocTableField_SetCell(swigCPtr, this, row, col, DocTextField.getCPtr(text_field), text_field);
  }

  public void ResizeRows(int rows) {
    jnidocengineJNI.DocTableField_ResizeRows__SWIG_0(swigCPtr, this, rows);
  }

  public void ResizeRows(int rows, DocTextField filler) {
    jnidocengineJNI.DocTableField_ResizeRows__SWIG_1(swigCPtr, this, rows, DocTextField.getCPtr(filler), filler);
  }

  public void ResizeCols(int cols) {
    jnidocengineJNI.DocTableField_ResizeCols__SWIG_0(swigCPtr, this, cols);
  }

  public void ResizeCols(int cols, DocTextField filler) {
    jnidocengineJNI.DocTableField_ResizeCols__SWIG_1(swigCPtr, this, cols, DocTextField.getCPtr(filler), filler);
  }

  public String GetColName(int col) {
    return jnidocengineJNI.DocTableField_GetColName(swigCPtr, this, col);
  }

  public void SetColName(int col, String col_name) {
    jnidocengineJNI.DocTableField_SetColName(swigCPtr, this, col, col_name);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocTableField_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

  public int GetHeaderRowsCount() {
    return jnidocengineJNI.DocTableField_GetHeaderRowsCount(swigCPtr, this);
  }

  public int GetHeaderColsCount() {
    return jnidocengineJNI.DocTableField_GetHeaderColsCount(swigCPtr, this);
  }

  public DocTextField GetHeaderCell(int row, int col) {
    return new DocTextField(jnidocengineJNI.DocTableField_GetHeaderCell(swigCPtr, this, row, col), false);
  }

  public DocTextField GetHeaderMutableCell(int row, int col) {
    return new DocTextField(jnidocengineJNI.DocTableField_GetHeaderMutableCell(swigCPtr, this, row, col), false);
  }

  public DocTextField GetHeaderCellPtr(int row, int col) {
    long cPtr = jnidocengineJNI.DocTableField_GetHeaderCellPtr(swigCPtr, this, row, col);
    return (cPtr == 0) ? null : new DocTextField(cPtr, false);
  }

  public DocTextField GetHeaderMutableCellPtr(int row, int col) {
    long cPtr = jnidocengineJNI.DocTableField_GetHeaderMutableCellPtr(swigCPtr, this, row, col);
    return (cPtr == 0) ? null : new DocTextField(cPtr, false);
  }

  public void SetHeaderCell(int row, int col, DocTextField text_field) {
    jnidocengineJNI.DocTableField_SetHeaderCell(swigCPtr, this, row, col, DocTextField.getCPtr(text_field), text_field);
  }

  public void ResizeHeaderRows(int rows) {
    jnidocengineJNI.DocTableField_ResizeHeaderRows__SWIG_0(swigCPtr, this, rows);
  }

  public void ResizeHeaderRows(int rows, DocTextField filler) {
    jnidocengineJNI.DocTableField_ResizeHeaderRows__SWIG_1(swigCPtr, this, rows, DocTextField.getCPtr(filler), filler);
  }

  public void ResizeHeaderCols(int cols) {
    jnidocengineJNI.DocTableField_ResizeHeaderCols__SWIG_0(swigCPtr, this, cols);
  }

  public void ResizeHeaderCols(int cols, DocTextField filler) {
    jnidocengineJNI.DocTableField_ResizeHeaderCols__SWIG_1(swigCPtr, this, cols, DocTextField.getCPtr(filler), filler);
  }

}
