/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocumentsMutableIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocumentsMutableIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocumentsMutableIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocumentsMutableIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocumentsMutableIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocumentsMutableIterator(DocumentsMutableIterator other) {
    this(jnidocengineJNI.new_DocumentsMutableIterator(DocumentsMutableIterator.getCPtr(other), other), true);
  }

  public int GetID() {
    return jnidocengineJNI.DocumentsMutableIterator_GetID(swigCPtr, this);
  }

  public Document GetDocument() {
    return new Document(jnidocengineJNI.DocumentsMutableIterator_GetDocument(swigCPtr, this), false);
  }

  public Document GetMutableDocument() {
    return new Document(jnidocengineJNI.DocumentsMutableIterator_GetMutableDocument(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocumentsMutableIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocumentsMutableIterator rvalue) {
    return jnidocengineJNI.DocumentsMutableIterator_Equals(swigCPtr, this, DocumentsMutableIterator.getCPtr(rvalue), rvalue);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocumentsMutableIterator_GetTags(swigCPtr, this), false);
  }

}
