/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocVideoSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocVideoSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocVideoSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocVideoSession obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocVideoSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocProcessingSettings CreateProcessingSettings() {
    long cPtr = jnidocengineJNI.DocVideoSession_CreateProcessingSettings(swigCPtr, this);
    return (cPtr == 0) ? null : new DocProcessingSettings(cPtr, true);
  }

  public String GetActivationRequest() {
    return jnidocengineJNI.DocVideoSession_GetActivationRequest(swigCPtr, this);
  }

  public void Activate(String activation_response) {
    jnidocengineJNI.DocVideoSession_Activate(swigCPtr, this, activation_response);
  }

  public boolean IsActivated() {
    return jnidocengineJNI.DocVideoSession_IsActivated(swigCPtr, this);
  }

  public void ProcessImage(Image in_image, DocProcessingSettings settings) {
    jnidocengineJNI.DocVideoSession_ProcessImage(swigCPtr, this, Image.getCPtr(in_image), in_image, DocProcessingSettings.getCPtr(settings), settings);
  }

  public void Reset() {
    jnidocengineJNI.DocVideoSession_Reset(swigCPtr, this);
  }

  public DocResult GetCurrentResult() {
    return new DocResult(jnidocengineJNI.DocVideoSession_GetCurrentResult(swigCPtr, this), false);
  }

  public DocResult GetMutableCurrentResult() {
    return new DocResult(jnidocengineJNI.DocVideoSession_GetMutableCurrentResult(swigCPtr, this), false);
  }

}
