/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocViewsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocViewsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocViewsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocViewsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocViewsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocViewsIterator(DocViewsIterator other) {
    this(jnidocengineJNI.new_DocViewsIterator(DocViewsIterator.getCPtr(other), other), true);
  }

  public int GetID() {
    return jnidocengineJNI.DocViewsIterator_GetID(swigCPtr, this);
  }

  public DocView GetView() {
    return new DocView(jnidocengineJNI.DocViewsIterator_GetView(swigCPtr, this), false);
  }

  public DocTagsCollection GetTags() {
    return new DocTagsCollection(jnidocengineJNI.DocViewsIterator_GetTags(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocViewsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocViewsIterator rvalue) {
    return jnidocengineJNI.DocViewsIterator_Equals(swigCPtr, this, DocViewsIterator.getCPtr(rvalue), rvalue);
  }

}
