/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocTableFieldsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocTableFieldsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocTableFieldsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocTableFieldsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocTableFieldsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocTableFieldsIterator(DocTableFieldsIterator other) {
    this(jnidocengineJNI.new_DocTableFieldsIterator(DocTableFieldsIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jnidocengineJNI.DocTableFieldsIterator_GetKey(swigCPtr, this);
  }

  public DocTableField GetField() {
    return new DocTableField(jnidocengineJNI.DocTableFieldsIterator_GetField(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocTableFieldsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocTableFieldsIterator rvalue) {
    return jnidocengineJNI.DocTableFieldsIterator_Equals(swigCPtr, this, DocTableFieldsIterator.getCPtr(rvalue), rvalue);
  }

}
