/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocFeedbackContainer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocFeedbackContainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocFeedbackContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocFeedbackContainer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocFeedbackContainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringsMapIterator FeedbackFieldIteratorBegin() {
    return new StringsMapIterator(jnidocengineJNI.DocFeedbackContainer_FeedbackFieldIteratorBegin(swigCPtr, this), true);
  }

  public StringsMapIterator FeedbackFieldIteratorEnd() {
    return new StringsMapIterator(jnidocengineJNI.DocFeedbackContainer_FeedbackFieldIteratorEnd(swigCPtr, this), true);
  }

  public QuadranglesMapIterator FeedbackQuadIteratorBegin() {
    return new QuadranglesMapIterator(jnidocengineJNI.DocFeedbackContainer_FeedbackQuadIteratorBegin(swigCPtr, this), true);
  }

  public QuadranglesMapIterator FeedbackQuadIteratorEnd() {
    return new QuadranglesMapIterator(jnidocengineJNI.DocFeedbackContainer_FeedbackQuadIteratorEnd(swigCPtr, this), true);
  }

  public void SetFeedbackField(String key, String field) {
    jnidocengineJNI.DocFeedbackContainer_SetFeedbackField(swigCPtr, this, key, field);
  }

  public void SetFeedbackQuad(String key, Quadrangle quad) {
    jnidocengineJNI.DocFeedbackContainer_SetFeedbackQuad(swigCPtr, this, key, Quadrangle.getCPtr(quad), quad);
  }

}
