/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocGraphicalStructure {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocGraphicalStructure(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocGraphicalStructure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocGraphicalStructure obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocGraphicalStructure(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetCollectionsCount() {
    return jnidocengineJNI.DocGraphicalStructure_GetCollectionsCount(swigCPtr, this);
  }

  public boolean HasCollection(int c_id) {
    return jnidocengineJNI.DocGraphicalStructure_HasCollection(swigCPtr, this, c_id);
  }

  public DocObjectsCollection GetCollection(int c_id) {
    return new DocObjectsCollection(jnidocengineJNI.DocGraphicalStructure_GetCollection(swigCPtr, this, c_id), false);
  }

  public DocObjectsCollection GetMutableCollection(int c_id) {
    return new DocObjectsCollection(jnidocengineJNI.DocGraphicalStructure_GetMutableCollection(swigCPtr, this, c_id), false);
  }

  public DocTagsCollection GetCollectionTags(int c_id) {
    return new DocTagsCollection(jnidocengineJNI.DocGraphicalStructure_GetCollectionTags(swigCPtr, this, c_id), false);
  }

  public DocObjectsCollectionsMutableIterator AddCollection(DocObjectsCollection collection) {
    return new DocObjectsCollectionsMutableIterator(jnidocengineJNI.DocGraphicalStructure_AddCollection__SWIG_0(swigCPtr, this, DocObjectsCollection.getCPtr(collection), collection), true);
  }

  public DocObjectsCollectionsMutableIterator AddCollection(DocObjectsCollection collection, DocTagsCollection tags) {
    return new DocObjectsCollectionsMutableIterator(jnidocengineJNI.DocGraphicalStructure_AddCollection__SWIG_1(swigCPtr, this, DocObjectsCollection.getCPtr(collection), collection, DocTagsCollection.getCPtr(tags), tags), true);
  }

  public void SetCollection(int c_id, DocObjectsCollection collection) {
    jnidocengineJNI.DocGraphicalStructure_SetCollection(swigCPtr, this, c_id, DocObjectsCollection.getCPtr(collection), collection);
  }

  public void RemoveCollection(int c_id) {
    jnidocengineJNI.DocGraphicalStructure_RemoveCollection(swigCPtr, this, c_id);
  }

  public DocObjectsCollectionsIterator ObjectsCollectionsBegin() {
    return new DocObjectsCollectionsIterator(jnidocengineJNI.DocGraphicalStructure_ObjectsCollectionsBegin(swigCPtr, this), true);
  }

  public DocObjectsCollectionsIterator ObjectsCollectionsEnd() {
    return new DocObjectsCollectionsIterator(jnidocengineJNI.DocGraphicalStructure_ObjectsCollectionsEnd(swigCPtr, this), true);
  }

  public DocObjectsCollectionsMutableIterator MutableObjectsCollectionsBegin() {
    return new DocObjectsCollectionsMutableIterator(jnidocengineJNI.DocGraphicalStructure_MutableObjectsCollectionsBegin(swigCPtr, this), true);
  }

  public DocObjectsCollectionsMutableIterator MutableObjectsCollectionsEnd() {
    return new DocObjectsCollectionsMutableIterator(jnidocengineJNI.DocGraphicalStructure_MutableObjectsCollectionsEnd(swigCPtr, this), true);
  }

  public DocObjectsCollectionsSliceIterator ObjectsCollectionsSlice(String tag) {
    return new DocObjectsCollectionsSliceIterator(jnidocengineJNI.DocGraphicalStructure_ObjectsCollectionsSlice(swigCPtr, this, tag), true);
  }

  public DocObjectsCollectionsMutableSliceIterator MutableObjectsCollectionsSlice(String tag) {
    return new DocObjectsCollectionsMutableSliceIterator(jnidocengineJNI.DocGraphicalStructure_MutableObjectsCollectionsSlice(swigCPtr, this, tag), true);
  }

  public DocViewsCollection GetViewsCollection() {
    return new DocViewsCollection(jnidocengineJNI.DocGraphicalStructure_GetViewsCollection(swigCPtr, this), false);
  }

  public DocViewsCollection GetMutableViewsCollection() {
    return new DocViewsCollection(jnidocengineJNI.DocGraphicalStructure_GetMutableViewsCollection(swigCPtr, this), false);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocGraphicalStructure_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
