/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocMultiStringTextObject extends DocBasicObject {
  private transient long swigCPtr;

  public DocMultiStringTextObject(long cPtr, boolean cMemoryOwn) {
    super(jnidocengineJNI.DocMultiStringTextObject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocMultiStringTextObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocMultiStringTextObject obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocMultiStringTextObject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String ObjectTypeStatic() {
    return jnidocengineJNI.DocMultiStringTextObject_ObjectTypeStatic();
  }

  public int GetStringsCount() {
    return jnidocengineJNI.DocMultiStringTextObject_GetStringsCount(swigCPtr, this);
  }

  public void SetStringsCount(int count) {
    jnidocengineJNI.DocMultiStringTextObject_SetStringsCount(swigCPtr, this, count);
  }

  public DocTextObject GetStringObject(int index) {
    return new DocTextObject(jnidocengineJNI.DocMultiStringTextObject_GetStringObject(swigCPtr, this, index), false);
  }

  public DocTextObject GetMutableStringObject(int index) {
    return new DocTextObject(jnidocengineJNI.DocMultiStringTextObject_GetMutableStringObject(swigCPtr, this, index), false);
  }

  public void SetStringObject(int index, DocTextObject text_object) {
    jnidocengineJNI.DocMultiStringTextObject_SetStringObject(swigCPtr, this, index, DocTextObject.getCPtr(text_object), text_object);
  }

}
