/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocObjectsCollection {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocObjectsCollection(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocObjectsCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocObjectsCollection obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocObjectsCollection(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String BaseClassNameStatic() {
    return jnidocengineJNI.DocObjectsCollection_BaseClassNameStatic();
  }

  public static DocObjectsCollection Create(String object_type) {
    long cPtr = jnidocengineJNI.DocObjectsCollection_Create(object_type);
    return (cPtr == 0) ? null : new DocObjectsCollection(cPtr, true);
  }

  public DocBasicObject CreateObject() {
    long cPtr = jnidocengineJNI.DocObjectsCollection_CreateObject(swigCPtr, this);
    return (cPtr == 0) ? null : new DocBasicObject(cPtr, true);
  }

  public DocObjectsCollection Clone() {
    long cPtr = jnidocengineJNI.DocObjectsCollection_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new DocObjectsCollection(cPtr, true);
  }

  public String ObjectType() {
    return jnidocengineJNI.DocObjectsCollection_ObjectType(swigCPtr, this);
  }

  public int GetFrameID() {
    return jnidocengineJNI.DocObjectsCollection_GetFrameID(swigCPtr, this);
  }

  public void SetFrameID(int frame_id) {
    jnidocengineJNI.DocObjectsCollection_SetFrameID(swigCPtr, this, frame_id);
  }

  public int GetObjectsCount() {
    return jnidocengineJNI.DocObjectsCollection_GetObjectsCount(swigCPtr, this);
  }

  public boolean HasObject(int obj_id) {
    return jnidocengineJNI.DocObjectsCollection_HasObject(swigCPtr, this, obj_id);
  }

  public DocBasicObject GetObject(int obj_id) {
    return new DocBasicObject(jnidocengineJNI.DocObjectsCollection_GetObject(swigCPtr, this, obj_id), false);
  }

  public DocBasicObject GetMutableObject(int obj_id) {
    return new DocBasicObject(jnidocengineJNI.DocObjectsCollection_GetMutableObject(swigCPtr, this, obj_id), false);
  }

  public DocTagsCollection GetObjectTags(int obj_id) {
    return new DocTagsCollection(jnidocengineJNI.DocObjectsCollection_GetObjectTags(swigCPtr, this, obj_id), false);
  }

  public DocBasicObjectsMutableIterator AddObject(DocBasicObject obj) {
    return new DocBasicObjectsMutableIterator(jnidocengineJNI.DocObjectsCollection_AddObject(swigCPtr, this, DocBasicObject.getCPtr(obj), obj), true);
  }

  public void SetObject(int obj_id, DocBasicObject obj) {
    jnidocengineJNI.DocObjectsCollection_SetObject(swigCPtr, this, obj_id, DocBasicObject.getCPtr(obj), obj);
  }

  public void RemoveObject(int obj_id) {
    jnidocengineJNI.DocObjectsCollection_RemoveObject(swigCPtr, this, obj_id);
  }

  public void RemoveObjectDeep(int obj_id, DocViewsCollection views_collection) {
    jnidocengineJNI.DocObjectsCollection_RemoveObjectDeep(swigCPtr, this, obj_id, DocViewsCollection.getCPtr(views_collection), views_collection);
  }

  public DocBasicObjectsIterator BasicObjectsBegin() {
    return new DocBasicObjectsIterator(jnidocengineJNI.DocObjectsCollection_BasicObjectsBegin(swigCPtr, this), true);
  }

  public DocBasicObjectsIterator BasicObjectsEnd() {
    return new DocBasicObjectsIterator(jnidocengineJNI.DocObjectsCollection_BasicObjectsEnd(swigCPtr, this), true);
  }

  public DocBasicObjectsMutableIterator MutableBasicObjectsBegin() {
    return new DocBasicObjectsMutableIterator(jnidocengineJNI.DocObjectsCollection_MutableBasicObjectsBegin(swigCPtr, this), true);
  }

  public DocBasicObjectsMutableIterator MutableBasicObjectsEnd() {
    return new DocBasicObjectsMutableIterator(jnidocengineJNI.DocObjectsCollection_MutableBasicObjectsEnd(swigCPtr, this), true);
  }

  public DocBasicObjectsSliceIterator BasicObjectsSlice(String tag) {
    return new DocBasicObjectsSliceIterator(jnidocengineJNI.DocObjectsCollection_BasicObjectsSlice(swigCPtr, this, tag), true);
  }

  public DocBasicObjectsMutableSliceIterator MutableBasicObjectsSlice(String tag) {
    return new DocBasicObjectsMutableSliceIterator(jnidocengineJNI.DocObjectsCollection_MutableBasicObjectsSlice(swigCPtr, this, tag), true);
  }

  public void Serialize(Serializer serializer) {
    jnidocengineJNI.DocObjectsCollection_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
