/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocTextFieldsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocTextFieldsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocTextFieldsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocTextFieldsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocTextFieldsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocTextFieldsIterator(DocTextFieldsIterator other) {
    this(jnidocengineJNI.new_DocTextFieldsIterator(DocTextFieldsIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jnidocengineJNI.DocTextFieldsIterator_GetKey(swigCPtr, this);
  }

  public DocTextField GetField() {
    return new DocTextField(jnidocengineJNI.DocTextFieldsIterator_GetField(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocTextFieldsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocTextFieldsIterator rvalue) {
    return jnidocengineJNI.DocTextFieldsIterator_Equals(swigCPtr, this, DocTextFieldsIterator.getCPtr(rvalue), rvalue);
  }

}
