/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocImageObjectsIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocImageObjectsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocImageObjectsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocImageObjectsIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocImageObjectsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocImageObjectsIterator(DocImageObjectsIterator other) {
    this(jnidocengineJNI.new_DocImageObjectsIterator(DocImageObjectsIterator.getCPtr(other), other), true);
  }

  public DocImageObject GetImageObject() {
    return new DocImageObject(jnidocengineJNI.DocImageObjectsIterator_GetImageObject(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocImageObjectsIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocImageObjectsIterator rvalue) {
    return jnidocengineJNI.DocImageObjectsIterator_Equals(swigCPtr, this, DocImageObjectsIterator.getCPtr(rvalue), rvalue);
  }

}
