/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocPagesFeedbackContainer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocPagesFeedbackContainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocPagesFeedbackContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocPagesFeedbackContainer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocPagesFeedbackContainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetPageCount() {
    return jnidocengineJNI.DocPagesFeedbackContainer_GetPageCount(swigCPtr, this);
  }

  public DocPageFeedback GetPageFeedback(int idx) {
    return new DocPageFeedback(jnidocengineJNI.DocPagesFeedbackContainer_GetPageFeedback(swigCPtr, this, idx), false);
  }

}
