/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.doc;

import com.smartengines.common.*;

public class DocTextObjectsCrossPageIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DocTextObjectsCrossPageIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DocTextObjectsCrossPageIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DocTextObjectsCrossPageIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnidocengineJNI.delete_DocTextObjectsCrossPageIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DocTextObjectsCrossPageIterator(DocTextObjectsCrossPageIterator other) {
    this(jnidocengineJNI.new_DocTextObjectsCrossPageIterator(DocTextObjectsCrossPageIterator.getCPtr(other), other), true);
  }

  public int GetPhysicalPageID() {
    return jnidocengineJNI.DocTextObjectsCrossPageIterator_GetPhysicalPageID(swigCPtr, this);
  }

  public int GetObjectID() {
    return jnidocengineJNI.DocTextObjectsCrossPageIterator_GetObjectID(swigCPtr, this);
  }

  public DocTextObject GetTextObject() {
    return new DocTextObject(jnidocengineJNI.DocTextObjectsCrossPageIterator_GetTextObject(swigCPtr, this), false);
  }

  public void Advance() {
    jnidocengineJNI.DocTextObjectsCrossPageIterator_Advance(swigCPtr, this);
  }

  public boolean Equals(DocTextObjectsCrossPageIterator rvalue) {
    return jnidocengineJNI.DocTextObjectsCrossPageIterator_Equals(swigCPtr, this, DocTextObjectsCrossPageIterator.getCPtr(rvalue), rvalue);
  }

}
